#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains a custom header (on web-01 and web-02)
sudo apt-get update
# Install and start nginx
sudo apt-get -y install nginx && sudo service nginx start
echo "Holberton School" | sudo tee /var/www/html/index.html
sudo service nginx start
# redirection
c="\\\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"
sudo sed -i "42i $c" /etc/nginx/sites-available/default
# Modified cutom 404 page
sudo echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/custom_404.html
sudo sed -i '/server_name _;/a error_page 404 /custom_404.html;\nlocation = /custom_404.html {\nroot /usr/share/nginx/html;\ninternal;\n}' /etc/nginx/sites-available/default
# Activate header to response
sudo sed -i '18i add_header X-Served-By $HOSTNAME;' /etc/nginx/sites-enabled/default
sudo service nginx restart
