#!/usr/bin/env bash
# The Bash script displays 'Holberton School' 10 times, between the 9th and the
# 10th iteration must display 'Hi'
i=1
while [ $i -le 10 ]
do
    echo "Holberton School"
    if [ $i -eq 9 ]
	then
	echo "Hi"
    fi
    i=$((i + 1))
done
