#!/usr/bin/env bash
# The script gives information about the holbertonschool file.
fd="holbertonschool"
if [ -e "$f" ]
then
    echo "$f file exists"
if [ -s "$f" ]
then
    echo "$f file is not empty"
else
    echo "$f file is empty"
fi
if [ -f "$f" ]
then
    echo "$f is a regular file"
fi
else
    echo "$f file does not exist"
fi
