#!/usr/bin/env bash
# The script gives information about the holbertonschool file.
fd="holbertonschool"
if [ -e "$fd" ]
then
    echo "$fd file exists"
if [ -s "$fd" ]
then
    echo "$fd file is not empty"
else
    echo "$fd file is empty"
fi
if [ -f "$fd" ]
then
    echo "$fd is a regular file"
fi
else
    echo "$fd file does not exist"
fi
