#!/usr/bin/env bash
# The script set uo a 'ufw' firewall.
# Blocks all incoming traffic, except the following TCP ports:
#      22 (SSH)
#      443 (HTTPS SSL)
#      80 (HTTP)
sudo apt-get -y install ufw
sudo ufw default deny incoming # Handle traffic by default policies
sudo ufw allow 22 # Activating the TCP ports
sudo ufw allow 443
sudo ufw allow 80
sudo ufw enable # Enabling the process
