#!/usr/bin/env bash
# Write a Bash script that configures an Ubuntu server with some requirements.
cp /etc/hosts ~/hosts.new
sed -i 's/127.0.0.2/127.0.0.1/' ~/hosts.new
sed -i '2i 8.8.8.8 facebook.com' ~/hosts.new
sudo cp -f ~/hosts.new /etc/hosts
