#!/usr/bin/env bash
# Nginx must be running and listening on port 8080
pkill apache
sudo chmod 700 /etc/nginx/nginx.conf
chown nginx:nginx /etc/nginx/nginx.conf
sed -i "s/80/8080/" /etc/nginx/sites-available/default
sudo -u nginx service nginx start
